# Generated by Django 3.1.4 on 2021-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210411_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category_names',
        ),
    ]
