# Generated by Django 3.1.4 on 2021-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210411_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
